#!/usr/bin/env perl

use Data::Dumper;

use Sensors::Http;
use Exporter 'import';

my @sensors;

sub requireClass {
    my ($class) = @_;
    (my $file = $class) =~ s|::|/|g;
    $file .= '.pm';
    require $file;
}

sub readConfig {
  my $path = "monitor.cfg";
  my $fd;
  open $fd, "<$path" || die "Unable to open configuration file: $path";
  while (my $line = <$fd> ) {
    chomp $line;
    my @fields = split(/\s+/, $line);
    my $type = shift @fields;
    my $freq = shift @fields;
    my $sensor = { type => $type, frequency => $freq , parameters => \@fields};
    print Dumper($sensor);
    requireClass("Sensors::".$type);
  }
}

readConfig();
